// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
import "./globals.css";
export const metadata = { title: "TinyLink" };
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="mx-auto max-w-3xl p-4">
        <header className="mb-6 flex items-center justify-between">
          <h1 className="text-2xl font-bold">TinyLink</h1>
          <a className="underline" href="/healthz" target="_blank">healthz</a>
        </header>
        {children}
        <footer className="mt-10 text-sm opacity-70">© {new Date().getFullYear()} TinyLink</footer>
      </body>
    </html>
  );
}
